apiVersion: apps/v1
kind: deployment
spec:
  selector:
    matchLabels:
      app: nginx
    replicas: 2
    template:
      metadata:
      labels:
        key: key
    spec:
      containers:
      - name: nginx-deployment
        image: nginx:1.7.9
        ports:
        - containerPort: 80
