# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts= {
	"n1" => "192.168.77.10",
	"n2" => "192.168.77.11",
	"n3" => "192.168.77.12",
	"n4" => "192.168.77.13"
}

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  check_guest_additions = false
  functional_vboxsf = false

  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  config.vm.box = "bento/ubuntu-16.04"
  hosts.each do |name, ip|
  config.vm.hostname = name
  config.vm.define name do |machine|
   machine.vm.network :private_network, ip: ip
   machine.vm.provider :virtualbox do |v|
    v.cpus = 2
    v.name = name
   end
  end
 end
end
